[profile.default]
src = "src"
out = "out"
libs = ["lib"]
show_progress = true

# include remappings
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-upgradeable/contracts=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@chimera/=lib/chimera/src/",
]
# evm_version = "london"
[fuzz]
runs = 500
max_test_rejects = 999999999

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
